// Danh sách ngân hàng VN hỗ trợ bởi VietQR (img.vietqr.io), dùng mã ngắn (bankCode) chuẩn Napas 247.
export const VIETNAMESE_BANKS = [
  { code: "momo", name: "MoMo", isWallet: true },
  { code: "VCB", name: "Vietcombank" },
  { code: "ICB", name: "VietinBank" },
  { code: "BIDV", name: "BIDV" },
  { code: "VBA", name: "Agribank" },
  { code: "MB", name: "MB Bank" },
  { code: "TCB", name: "Techcombank" },
  { code: "ACB", name: "ACB" },
  { code: "VPB", name: "VPBank" },
  { code: "TPB", name: "TPBank" },
  { code: "STB", name: "Sacombank" },
  { code: "HDB", name: "HDBank" },
  { code: "SHB", name: "SHB" },
  { code: "EIB", name: "Eximbank" },
  { code: "MSB", name: "MSB" },
  { code: "SCB", name: "SCB" },
  { code: "OCB", name: "OCB" },
  { code: "SEAB", name: "SeABank" },
  { code: "VIB", name: "VIB" },
  { code: "ABB", name: "ABBank" },
  { code: "BAB", name: "Bac A Bank" },
  { code: "PVCB", name: "PVcomBank" },
  { code: "NVB", name: "NCB" },
  { code: "KLB", name: "Kien Long Bank" },
  { code: "VBB", name: "Vietbank" },
  { code: "BVB", name: "BaoViet Bank" },
  { code: "LPB", name: "LienVietPostBank" },
  { code: "GPB", name: "GPBank" },
  { code: "NAB", name: "Nam A Bank" },
  { code: "SGICB", name: "SaigonBank" },
  { code: "CAKE", name: "CAKE by VPBank", isWallet: true },
  { code: "Ubank", name: "Ubank by VPBank", isWallet: true },
  { code: "TIMO", name: "Timo", isWallet: true },
  { code: "VNPTMONEY", name: "VNPT Money", isWallet: true },
  { code: "VIETTELMONEY", name: "Viettel Money", isWallet: true },
];
